config/routes.rb
Rails.application.routes.draw do
  
  root to: "lessons#index"
  
  devise_for :users
  
  get 'user/:id/profanity/:profanity', to: 'users#update', as: 'profanity'
  
  resources :lessons do
    # get 'play', on: :member
    get 'play(/:reverse)', on: :member, to: 'lessons#play', as: 'play'
    post 'result', on: :member
    get 'stats', on: :member
    get 'reset', on: :member
    resources :translations, shallow: true
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :lesson
  has_many :answers, dependent: :destroy
  has_many :tests, through: :answers
  
  # attribute :answer, :string
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_translation, only: %i[ show edit update destroy ]
  before_action :set_lesson, except: %i[ destroy ]

  # GET /translations or /translations.json
  def index
    @translations = Translation.all
  end

  # GET /translations/1 or /translations/1.json
  def show
  end

  # GET /translations/new
  def new
    @translation = Translation.new
  end

  # GET /translations/1/edit
  def edit
  end

  # POST /translations or /translations.json
  def create
    @lesson.translations.create! params.required(:translation).permit([:original, :translated])
    redirect_to @lesson
    # @translation = Translation.new(translation_params)

    # respond_to do |format|
#       if @translation.save
#         format.html { redirect_to translation_url(@translation), notice: "Translation was successfully created." }
#         format.json { render :show, status: :created, location: @translation }
#       else
#         format.html { render :new, status: :unprocessable_entity }
#         format.json { render json: @translation.errors, status: :unprocessable_entity }
#       end
#     end
  end

  # PATCH/PUT /translations/1 or /translations/1.json
  def update
    respond_to do |format|
      if @translation.update(translation_params)
        format.html { redirect_to translation_url(@translation), notice: "Translation was successfully updated." }
        format.json { render :show, status: :ok, location: @translation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1 or /translations/1.json
  def destroy
    @translation.destroy

    respond_to do |format|
      format.html { redirect_to @translation.lesson, notice: "Translation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translation
      @translation = Translation.find(params[:id])
    end
    
    def set_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    # Only allow a list of trusted parameters through.
    def translation_params
      params.require(:translation).permit(:original, :translated, :lesson_id)
    end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_new.html.erb
<%= form_with model: [lesson, Translation.new] do |form| %>
<div class="row">
  <div class="col col-6 col-md-4">
    <%= form.label :original %>
    <%= form.text_field :original, class: 'form-control fs-4', autocomplete: :off, autocapitalize: :off %>
  </div>

  <div class="col col-6 col-md-4">
    <%= form.label 'Traduction' %>
    <%= form.text_field :translated, class: 'form-control fs-4', autocomplete: :off, autocapitalize: :off %>
  </div>

  <div class="col col-12 col-md-4 mt-md-2 text-center">
    <br/><%= form.submit "Ajouter", class:'btn btn-warning btn-lg fs-4' %>
  </div>
  
<% end %>

app/views/translations/_translation.html.erb
<div id="<%= dom_id translation %>" class="row border-bottom py-2">
	<p class="col col-6 col-md-4 display-5">
		<%= translation.original %>
	</p>

	<p class="col col-6 col-md-4 display-5">
		<%= translation.translated %>
	</p>
	
	<% if current_user == @lesson.user %>
    <div class="col col-12 col-md-4 mt-md-2 text-center">
		<%= button_to "Supprimer", translation, method: :delete, class:'btn btn-primary btn-lg fs-4', form: {style: 'display:inline-block;'} %>
    </div>
	<% end %>

</div>

app/views/translations/edit.html.erb
<h1>Editing translation</h1>

<%= render "form", translation: @translation %>

<br>

<div>
  <%= link_to "Show this translation", @translation %> |
  <%= link_to "Back to translations", translations_path %>
</div>

app/views/translations/index.html.erb
<h1>Translations</h1>

<div id="translations">
  <% @translations.each do |translation| %>
    <%= render translation %>
    <p>
      <%= link_to "Show this translation", translation %>
    </p>
  <% end %>
</div>

<%= link_to "New translation", new_translation_path %>

app/views/translations/new.html.erb
<h1>New translation</h1>

<%= render "form", translation: @translation %>

<br>

<div>
  <%= link_to "Back to translations", translations_path %>
</div>

app/views/translations/show.html.erb
<%= render @translation %>

<div>
  <%= link_to "Edit this translation", edit_translation_path(@translation) %> |
  <%= link_to "Back to translations", translations_path %>

  <%= button_to "Destroy this translation", @translation, method: :delete %>
</div>