config/routes.rb
Rails.application.routes.draw do
  
  root to: "lessons#index"
  
  devise_for :users
  
  get 'user/:id/profanity/:profanity', to: 'users#update', as: 'profanity'
  
  resources :lessons do
    # get 'play', on: :member
    get 'play(/:reverse)', on: :member, to: 'lessons#play', as: 'play'
    post 'result', on: :member
    get 'stats', on: :member
    get 'reset', on: :member
    resources :translations, shallow: true
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :translations
  accepts_nested_attributes_for :translations
  belongs_to :user
  
  has_many :tests
  
  def overall_score_for(user)
    self.tests.for_user(user).map{|t|t.score}.sum
  end
  
  def maximum_possible_score_for(user)
    self.tests.for_user(user).map{|t|t.answers.count}.sum
  end
  
  def percentage_score_for(user)
    unless self.tests.for_user(user).empty?
      (self.overall_score_for(user).to_f/self.maximum_possible_score_for(user).to_f*100).round(2)
    else
      ""
    end
  end
  
  def no_tests_for(user)
    self.tests.for_user(user).empty?
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  
  before_action :authenticate_user!
  
  before_action :set_lesson, only: %i[ show edit update destroy play result stats reset]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end
  
  def play
    @test = Test.new(:lesson => @lesson)
    @test.reverse = true if params[:reverse] == 'reverse'
    @test.translations = @lesson.translations.shuffle
    render 'lessons/play/index'
  end
  
  def result
    @test = @lesson.tests.build(score: 0, user_id: current_user.id, reverse: params['test']['reverse'])
    @test.answers.build params['test']['answers_attributes'].as_json.values
    @test.answers.each do |a|
      unless @test.reverse?
        if a.content.parameterize == a.translation.translated.parameterize
          a.correct = true
          @test.score += 1
        end
      else
        if a.content.parameterize == a.translation.original.parameterize
          a.correct = true
          @test.score += 1
        end
      end
    end
    if @test.save
      render 'lessons/play/result'
    else
      flash[:notice] = "Oups. Une erreur s'est produite. #{@test.to_json}"
      render 'lessons/play/index'
    end
  end
  
  def stats
    tests = @lesson.tests.for_user(current_user)
    @history = tests.sort_by(&:created_at).reverse
    @words = Array.new
    answers = tests.map{|t|t.answers}.flatten
    answers.group_by(&:translation_id).each do |translation_id, answers|
      word = {}
      correct_answers = answers.select{|a|a.correct?}
      incorrect_answers = answers.select{|a|!a.correct?}
      translation = Translation.find(translation_id)
      word[:original] = translation.original
      word[:translated] = translation.translated
      word[:percentage_score] = (correct_answers.size.to_f / answers.size.to_f*100).round(0)
      word[:absolute_score] = "#{correct_answers.size} / #{answers.size}"
      word[:translated_errors] = incorrect_answers.select{|a|!a.test.reverse?}.map(&:content).uniq.reject(&:blank?).join ", "
      word[:original_errors] = incorrect_answers.select{|a|a.test.reverse?}.map(&:content).uniq.reject(&:blank?).join ", "
      @words << word
    end
    @words.sort_by!{|word| word[:percentage_score]}
  end
  
  def reset
    @lesson.tests.for_user(current_user).destroy_all
    redirect_to stats_lesson_path(@lesson)
  end
  
  
  # GET /lessons/new
  def new
    @lesson = current_user.lessons.build
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = current_user.lessons.build(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def full_score_percentage(lesson,user)
    lesson.percentage_score_for(user).to_f.round(0)
  end
  
  def full_score_absolute(lesson,user)
    "#{lesson.overall_score_for(user)} / #{lesson.maximum_possible_score_for(user)}"
  end
  
  def set_color(score)
    if score.to_i >= 90
      'success'
    elsif score.to_i >= 60
      'warning'
    else
      'danger'
    end
  end
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson) do |form| %>
  <% if lesson.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit "Valider", class:'btn btn-warning btn-lg' %>
	
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<h1 id="<%= dom_id lesson %>" class="display-1">
    <%= lesson.title %>
</h1>
<p>
	Par <%= lesson.user.email %> - <%= pluralize @lesson.translations.count, "mot" %> |
	Score : <%= full_score_percentage(@lesson, current_user) %>%
	(<%= full_score_absolute(@lesson, current_user) %>)
<p>

app/views/lessons/_translations.html.erb
<div id="translations">
	<br/>
	<%= render lesson.translations %>
</div>

<%= render "translations/new", lesson: lesson if current_user == @lesson.user %>

app/views/lessons/edit.html.erb
<h1 class="display-4">Modifier le titre</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Modifier les mots", lesson_path(@lesson), class:'btn btn-primary btn-lg' %>
  <%= link_to "Toutes les leçons", lessons_path, class:'btn btn-primary btn-lg' %>
</div>

app/views/lessons/index.html.erb
		<h1 class="display-1 bd-title strong">ndls</h1>
		
		<div class="row">
		<div class="col-md-auto row align-items-center flex-row bg-success bg-gradient rounded-pill mx-1 mb-2 ps-0">
			<div style="width:80px;"><%= image_tag "profanity/#{current_user.profanity}.png", class:"img-fluid rounded-circle"%></div>
			<p class="col mt-4 bd-lead"><%= profanity_lead(current_user)%></p>
		</div>
	</div>
		
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
	
  <% @lessons.each do |lesson| %>
  <div class="col">
    <div class="card h-100 bg-info bg-gradient">
      <div class="card-body pb-0">
        <h3 class="card-title display-5"><%= lesson.title %></h3>
		<h4 class="card-subtitle fs-4 mb-3 my-3">
			<span class="badge bg-primary"><%= lesson.user.email %></span>
			<span class="badge bg-primary"><%= "#{pluralize lesson.translations.count, 'mot'}" %></span>
			<% unless lesson.no_tests_for(current_user) %>
				<span class="badge bg-<%= set_color(full_score_percentage(lesson,current_user))%>">
					<%= full_score_percentage(lesson,current_user) %></span>
			<% end %>
		</h4>
      </div>
      <div class="card-footer bg-transparent border-info">
		<div class="row px-0 mb-2">
			<% unless lesson.no_tests_for(current_user) %>
				<%= links_to_test_and_reverse(lesson) %>
			<% else %>
				<%= link_to "Voir les mots", lesson, class:'col btn btn-warning btn-lg mb-3 width-auto' %>
			<% end %>
		</div>
		<div class="row px-2">
			<%= link_to "Stats", stats_lesson_path(lesson), class:'col btn btn-primary btn-lg mb-3' %>
			<%= link_to "Modifier", lesson, class:'col btn btn-primary btn-lg mb-3 ms-3' if lesson.user == current_user %>
		</div>
      </div>
    </div>
  </div>
  <% end %>
  
  <div class="col">
    <div class="card h-100 bg-warning bg-gradient">
      <div class="card-body">
		<div class="row px-2 mt-auto h-100 d-flex align-items-center">
		<%= link_to "Ajouter une leçon", new_lesson_path, class:'btn btn-outline-secondary stretched-link btn-lg' %>
		</div>
      </div>
      <!-- <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div> -->
    </div>
  </div>
  
</div>

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Back to lessons", lessons_path %>
</div>

app/views/lessons/show.html.erb
<%= render @lesson %>

<div>
  <%= links_to_test_and_reverse(@lesson) %>
  <%= link_to "Stats", stats_lesson_path(@lesson), class:'btn btn-primary btn-lg mb-2 mb-md-0 fs-4' %>
  
  <% if current_user == @lesson.user %>
  	<%= link_to "Modifier", edit_lesson_path(@lesson), class:'btn btn-primary btn-lg mb-2 mb-md-0 fs-4' %>
  	<%= button_to "Supprimer", @lesson, method: :delete, class:'btn btn-danger btn-lg mb-2 mb-md-0 fs-4', form: {style: 'display:inline-block;'} %>
  <% end %>
  
  <%= link_to "Toutes les leçons", lessons_path, class:'btn btn-primary btn-lg mb-2 mb-md-0 fs-4' %>
</div>

<%= render "lessons/translations", lesson: @lesson %>

app/views/lessons/stats.html.erb
<%= render @lesson %>

<div>
  <%= links_to_test_and_reverse(@lesson) %>
  <%= link_to "Remettre à zéro", reset_lesson_path(@lesson), class:'btn btn-primary btn-lg mb-2 mb-md-0 fs-4'  %>
  <%= link_to "Toutes les leçons", lessons_path, class:'btn btn-primary btn-lg mb-2 mb-md-0 fs-4' %>
</div>

<h2 class="display-5 mt-5 border-bottom">Ton score<h2>
	<% unless @lesson.tests.empty? %>
	<p class="display-1 "><%= full_score_percentage(@lesson, current_user) %>% (<%= full_score_absolute(@lesson, current_user) %>)</p>
	
	
	<div class="row">
		<div class="col-md-auto row align-items-center flex-row bg-success bg-gradient rounded-pill mx-1 mb-2 ps-0">
			<div style="width:80px;"><%= image_tag "profanity/#{current_user.profanity}.png", class:"img-fluid rounded-circle"%></div>
			<p class="col mt-4 bd-lead"><%= profanity_feedback(full_score_percentage(@lesson, current_user),current_user) %></p>
		</div>
	</div>
	
	<% else %>
	<p>Tu n'as pas encore passé de test.</p>
	<% end %>

<h2 class="display-5 mt-5 border-bottom">Historique des tests</h2>
	
<% @history.each do |test| %>
	<div class="row pt-2 border-bottom">
		<div class="col-6 col-md-3 fs-3"><%= format_date test.created_at %></div>
		<div class="col"><span class="badge badge-pill <%= test.reverse? ? "bg-warning text-dark" : "bg-primary" %>"><%= test.reverse? ? "<-" : "->" %></span></div>
		<div class="col fs-2"><%= test.percentage_score %>%</div>
		<div class="col strong"><%= test.score %> / <%= test.maximum_score %></div>
		<div class="col-md-4 col-12">
			<div class="progress my-2">
			  <div class="progress-bar bg-<%= set_color(test.percentage_score)%>" role="progressbar" style="width: <%= test.percentage_score %>%" aria-valuenow="<%= test.percentage_score%>" aria-valuemin="0" aria-valuemax="100"></div>
			</div>
			
			
		</div>
	</div>	
<% end %>

<h2 class="display-5 mt-5 border-bottom">Détail par mot</h2>
	
<% @words.each do |word| %>
	<div class="row flex-row">
		<div class="col-6 col-md-4 order-3 order-md-1 text-end fs-2"><%= word[:original] %></div>
		<div class="col-6 col-md-2 order-1 order-md-2 mt-md-2 text-end"><%= word[:percentage_score] %>%</div>
		<div class="col-6 col-md-2 order-2 order-md-3 mt-md-2"><%= word[:absolute_score] %></div>
		<div class="col-6 col-md-4 order-4 order-md-4 fs-2"><%= word[:translated] %></div>
	</div>
	<div class="row flex-row border-bottom">
		<div class="col-6 col-md-4 text-warning text-decoration-line-through text-end"><%= word[:original_errors] %></div>
		<div class="d-none d-md-block col-md-4"></div>
		<div class="col-6 col-md-4 text-warning text-decoration-line-through"><%= word[:translated_errors] %></div>
	</div>
<% end %>