config/routes.rb
Rails.application.routes.draw do
  
  root to: "lessons#index"
  
  devise_for :users
  
  get 'user/:id/profanity/:profanity', to: 'users#update', as: 'profanity'
  
  resources :lessons do
    # get 'play', on: :member
    get 'play(/:reverse)', on: :member, to: 'lessons#play', as: 'play'
    post 'result', on: :member
    get 'stats', on: :member
    get 'reset', on: :member
    resources :translations, shallow: true
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :translations
  accepts_nested_attributes_for :translations
  belongs_to :user
  
  has_many :tests
  
  def overall_score_for(user)
    self.tests.for_user(user).map{|t|t.score}.sum
  end
  
  def maximum_possible_score_for(user)
    self.tests.for_user(user).map{|t|t.answers.count}.sum
  end
  
  def percentage_score_for(user)
    unless self.tests.for_user(user).empty?
      (self.overall_score_for(user).to_f/self.maximum_possible_score_for(user).to_f*100).round(2)
    else
      ""
    end
  end
  
  def no_tests_for(user)
    self.tests.for_user(user).empty?
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  
  before_action :authenticate_user!
  
  before_action :set_lesson, only: %i[ show edit update destroy play result stats reset]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end
  
  def play
    @test = Test.new(:lesson => @lesson)
    @test.reverse = true if params[:reverse] == 'reverse'
    @test.translations = @lesson.translations.shuffle
    render 'lessons/play/index'
  end
  
  def result
    @test = @lesson.tests.build(score: 0, user_id: current_user.id, reverse: params['test']['reverse'])
    @test.answers.build params['test']['answers_attributes'].as_json.values
    @test.answers.each do |a|
      unless @test.reverse?
        if a.content.parameterize == a.translation.translated.parameterize
          a.correct = true
          @test.score += 1
        end
      else
        if a.content.parameterize == a.translation.original.parameterize
          a.correct = true
          @test.score += 1
        end
      end
    end
    if @test.save
      render 'lessons/play/result'
    else
      flash[:notice] = "Oups. Une erreur s'est produite. #{@test.to_json}"
      render 'lessons/play/index'
    end
  end
  
  def stats
    tests = @lesson.tests.for_user(current_user)
    @history = tests.sort_by(&:created_at).reverse
    @words = Array.new
    answers = tests.map{|t|t.answers}.flatten
    answers.group_by(&:translation_id).each do |translation_id, answers|
      word = {}
      correct_answers = answers.select{|a|a.correct?}
      incorrect_answers = answers.select{|a|!a.correct?}
      translation = Translation.find(translation_id)
      word[:original] = translation.original
      word[:translated] = translation.translated
      word[:percentage_score] = (correct_answers.size.to_f / answers.size.to_f*100).round(0)
      word[:absolute_score] = "#{correct_answers.size} / #{answers.size}"
      word[:translated_errors] = incorrect_answers.select{|a|!a.test.reverse?}.map(&:content).uniq.reject(&:blank?).join ", "
      word[:original_errors] = incorrect_answers.select{|a|a.test.reverse?}.map(&:content).uniq.reject(&:blank?).join ", "
      @words << word
    end
    @words.sort_by!{|word| word[:percentage_score]}
  end
  
  def reset
    @lesson.tests.for_user(current_user).destroy_all
    redirect_to stats_lesson_path(@lesson)
  end
  
  
  # GET /lessons/new
  def new
    @lesson = current_user.lessons.build
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = current_user.lessons.build(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def full_score_percentage(lesson,user)
    lesson.percentage_score_for(user).to_f.round(0)
  end
  
  def full_score_absolute(lesson,user)
    "#{lesson.overall_score_for(user)} / #{lesson.maximum_possible_score_for(user)}"
  end
  
  def set_color(score)
    if score.to_i >= 90
      'success'
    elsif score.to_i >= 60
      'warning'
    else
      'danger'
    end
  end
end

app/views/lessons/play/_test.html.erb
<%= form_with model: test, url: result_lesson_path(test.lesson) , method: :post, autocomplete: :off do |form| %>
	
	<%= form.hidden_field :user, value: current_user %>
	<%= form.hidden_field :reverse, value: test.reverse %>
	<div class="pt-3 mb-3 border-bottom"></div>
	<%= form.fields_for :answers do |answer_subform| %>
	<div id="<%= dom_id answer_subform.object %>" class="row border-bottom form-group">
		<p class="col-12 col-md-6 col-form-label-lg text-center">
			<span class="display-5">
				<% unless test.reverse? %>
					<%= answer_subform.object.translation.original %> 
				<% else %>
					<%= answer_subform.object.translation.translated %>
				<% end %>
			</span>
		</p>

		<p class="col-12 col-md-6 form-control-lg">
			<%= answer_subform.text_field :content, autocomplete: :off, autocapitalize: :off , class: 'form-control text-center fs-3' %>
		</p>
		<%= answer_subform.hidden_field :translation_id %>
	</div>
	<% end %>
	<div class="row pt-3 text-center">
		<p class="col">
			<%= form.submit "Résultats", class:'btn btn-primary btn-lg fs-4'%>
		</p>

	</div>
<% end %>

app/views/lessons/play/index.html.erb
<%= render @lesson %>

<%= render "lessons/play/test", test: @test %>

app/views/lessons/play/result.html.erb
<h1 class="display-1">Ton score : <%= @test.score %> sur <%= @test.answers.count %></h1>


	<div class="row">
		<div class="col-md-auto row align-items-center flex-row bg-success bg-gradient rounded-pill mx-1 mb-2 ps-0">
			<div style="width:80px;"><%= image_tag "profanity/#{current_user.profanity}.png", class:"img-fluid rounded-circle"%></div>
			<p class="col mt-4 bd-lead"><%= profanity_feedback(@test.percentage_score,current_user) %></p>
		</div>
	</div>



<div class="pt-3 border-bottom"></div>

<% @test.answers.each do |answer| %>
<div class="row border-bottom pt-md-3">
	<p class="col col-12 col-md-6 text-center display-5">
		<%= @test.reverse? ? answer.translation.translated : answer.translation.original %>
	</p>

	<p class="col col-12 col-md-6 bg-<%= answer.correct? ? 'success text-white' : 'warning' %> bg-gradient rounded text-center display-5">
		<span class="<%= 'text-decoration-line-through text-secondary' unless answer.correct? %>"><%= answer.content %></span>
		<%= @test.reverse? ? answer.translation.original : answer.translation.translated unless answer.correct? %>
	</p>
</div>
<% end %>

<div class="mt-3 text-center text-md-right">
	<%= links_to_test_and_reverse(@lesson) %>
	<%= link_to "Stats", stats_lesson_path(@lesson), class:'btn btn-primary btn-lg mb-md-0 mb-2 fs-4' %>
	<%= link_to "Modifier", @lesson, class:'btn btn-primary btn-lg mb-md-0 mb-2 fs-4' %>
	<%= link_to "Retour", lessons_path, class:'btn btn-primary btn-lg mb-md-0 mb-2 fs-4' %>
</div>