config/routes.rb
Rails.application.routes.draw do
  
  root to: "lessons#index"
  
  devise_for :users
  
  get 'user/:id/profanity/:profanity', to: 'users#update', as: 'profanity'
  
  resources :lessons do
    # get 'play', on: :member
    get 'play(/:reverse)', on: :member, to: 'lessons#play', as: 'play'
    post 'result', on: :member
    get 'stats', on: :member
    get 'reset', on: :member
    resources :translations, shallow: true
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NDLS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
	  
	  
	  <div class="container fs-4 mt-3" style="">
		  <% unless notice.nil? %>
		  	<p class="alert alert-primary"><%= notice %></p>
		  <% end %>
		  <% unless alert.nil? %>
		  	<p class="alert alert-warning"><%= alert %></p>
		  <% end %>
		  
    	  <%= yield %>
		  
		  <% if current_user %>
		    <div class="my-5 text-center">
				<button type="button" class="btn btn-primary mb-2" disabled>
				  <%= current_user.email %>
				</button>
				
				<div class="btn-group mb-2" role="group">
					<div class="btn btn-primary">Humeur</div>
					<% ["bisounours","neutre","fais_moi_mal"].each do |level| %>
						<% if current_user.profanity== level %>
							<div class="btn btn-primary"><%= level %></div>
						<% else %>
							<%= link_to level, profanity_path(id:current_user.id,profanity:level), class:'btn btn-outline-primary' %>
						<% end %>
					<% end %>
				</div>
				
				
				<%= button_to('Déconnexion',  destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger mb-2', form_class:'disconnect'	)%>
			</div>
		  <% end %>
		  
		  <%= link_to "Connexion", new_user_session_path, class: 'btn btn-primary m-5' if current_user.nil? unless (controller_name == 'sessions' or controller_name == 'registrations') %>
		  
	  </div>
  </body>
</html>